backend:
  name: git-gateway
  branch: main # or master, whichever your branch is named

media_folder: "assets/images" # Where your Lambo and logo images will be stored
public_folder: "/assets/images"

collections:
  - name: "portfolio_data"
    label: "Portfolio Projects"
    files:
      - name: "project_list"
        label: "Project List"
        file: "projects.json" # This is the file our JS will read
        fields:
          - name: "projects"
            label: "Projects"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Category", name: "category", widget: "select", options: ["branding", "social", "logo", "motion"]}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Description", name: "description", widget: "text"}
